"use strict";
exports.__esModule = true;
var clases_1 = require("./clases");
var clases_2 = require("./clases");
var clases_3 = require("./clases");
var fs = require("fs");
var profe1 = new clases_1.Professional("Brad Pitt", 57, "Male", 78, 180, "Brown", "Blue", "White", false, "American", 1, "Actor");
var profe2 = new clases_1.Professional("Angelina Jolie", 45, "Famale", 56, 169, "Brown", "Blue", "White", false, "American", 1, "Actress");
var profe3 = new clases_1.Professional("Morgan Freeman", 83, "Male", 79, 188, "White", "Brown", "Black", false, "American", 1, "Actor");
var profe4 = new clases_1.Professional("Clint Eastwood", 90, "Male", 78, 172, "White", "Blue", "White", true, "American", 5, "Director");
profe1.toString();
profe2.toString();
profe3.toString();
profe4.toString();
var movie1 = new clases_2.Movie("Gran Torino", 2008, "American", ["Drama", "Police"]);
var movie2 = new clases_2.Movie("Pulp Fiction", 1994, "American", ["Action", "Drama", "Crime"]);
var movie3 = new clases_2.Movie("Mr. & Mrs. Smith", 2005, "American", ["Action", "Comedi"]);
var movie4 = new clases_2.Movie("A Clockwork Orange", 1971, "American", ["Drama", "Police", "Thriller"]);
movie1.toString();
var imdb = new clases_3.Imdb([new clases_2.Movie("Green Book", 2018, "American", ["Comedia", "Dramatica"]), new clases_2.Movie("Jurassic Park", 1993, "American", ["Action", "Aventura", "Ciencia ficción"]), new clases_2.Movie("Split", 2016, "American", ["Action", "Terror", "Crime"])]);
var jsonStr = JSON.stringify(imdb);
fs.writeFileSync("C:\\Users\\barbo\\Documents\\imdbBBDD.json", jsonStr);
